# Generated by Django 5.1.3 on 2024-11-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delights', '0003_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
